import Product from '../models/Product.js';
import mongoose from 'mongoose';
import dotenv from 'dotenv';

dotenv.config();

const toSlug = (name) =>
  name.toLowerCase().replace(/[^\w\s-]/g, '').replace(/\s+/g, '-');

// Base URL for your own images served by Express static
const img = (file) => `/images/${file}`;

// Unique Unsplash URLs - Each product gets its own image
const unsplashImages = {
  serum1: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=80',
  serum2: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=1200&q=80',
  serum3: 'https://images.unsplash.com/photo-1616401776201-49e6aeee2c5f?auto=format&fit=crop&w=1200&q=80',
  serum4: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=1200&q=80',
  serum5: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?auto=format&fit=crop&w=1200&q=80',
  moisturizer1: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=1200&q=80',
  moisturizer2: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1200&q=80',
  moisturizer3: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=1200&q=80',
  mask1: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=1200&q=80',
  mask2: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=1200&q=80',
  cleanser1: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1200&q=80',
  cleanser2: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=1200&q=80',
  suncare1: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=1200&q=80',
  toner1: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=80',
  eye1: 'https://images.unsplash.com/photo-1590440165072-f5a8b5bfb399?auto=format&fit=crop&w=1200&q=80',
  eye2: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?auto=format&fit=crop&w=1200&q=80',
};

const products = [
  // ─── SERUMS ───────────────────────────────────────────
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Radiance Serum',
    slug: toSlug('Radiance Serum'),
    subtitle: 'Vitamin C & Niacinamide',
    description: 'Lightweight botanical serum with vitamin C and niacinamide for brightening and antioxidant protection',
    price: 89,
    comparePrice: 110,
    category: 'serums',
    stock: 25,
    image: unsplashImages.serum1,
    images: [unsplashImages.serum1, unsplashImages.serum2],
    featured: true,
    tag: 'Best Seller',
    tagType: 'best',
    rating: 4.8,
    numReviews: 124,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Retinol Night Elixir',
    slug: toSlug('Retinol Night Elixir'),
    subtitle: '0.5% Retinol & Peptides',
    description: 'Overnight renewal elixir with retinol and peptides for visible anti-ageing results',
    price: 98,
    category: 'serums',
    stock: 20,
    image: unsplashImages.serum2,
    images: [unsplashImages.serum2],
    featured: true,
    tag: 'New',
    tagType: 'new',
    rating: 4.9,
    numReviews: 203,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Gold Luxury Elixir',
    slug: toSlug('Gold Luxury Elixir'),
    subtitle: '24K Gold & Hyaluronic Acid',
    description: 'Ultra-luxurious serum with 24K gold particles and hyaluronic acid for a radiant complexion',
    price: 120,
    comparePrice: 149,
    category: 'serums',
    stock: 15,
    image: img('gold-elixir.png'),
    images: [img('gold-elixir.png')],
    featured: true,
    tag: 'Best Seller',
    tagType: 'best',
    rating: 4.9,
    numReviews: 156,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Renewal Night Serum',
    slug: toSlug('Renewal Night Serum'),
    subtitle: 'Bakuchiol & Peptides',
    description: 'Natural retinol alternative with bakuchiol and peptides for overnight skin renewal',
    price: 92,
    category: 'serums',
    stock: 20,
    image: img('serum1.png'),
    images: [img('serum1.png')],
    featured: true,
    tag: 'New',
    tagType: 'new',
    rating: 4.8,
    numReviews: 98,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Vitamin C Radiance Serum',
    slug: toSlug('Vitamin C Radiance Serum'),
    subtitle: '20% Stabilised Vitamin C',
    description: 'High-potency vitamin C serum with 20% stabilised ascorbic acid for a luminous complexion',
    price: 95,
    category: 'serums',
    stock: 18,
    image: img('serum22.png'),
    images: [img('serum22.png')],
    featured: true,
    tag: 'Best Seller',
    tagType: 'best',
    rating: 4.9,
    numReviews: 187,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Barrier Repair Serum',
    slug: toSlug('Barrier Repair Serum'),
    subtitle: 'Ceramide & Centella',
    description: 'Reparative serum with ceramides and centella asiatica to restore a damaged skin barrier',
    price: 76,
    category: 'serums',
    stock: 22,
    image: img('serum2.png'),
    images: [img('serum2.png')],
    featured: false,
    rating: 4.8,
    numReviews: 132,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Glow Booster Serum',
    slug: toSlug('Glow Booster Serum'),
    subtitle: 'Niacinamide & AHA Complex',
    description: 'Exfoliating and brightening serum with niacinamide and AHA for a visible glow',
    price: 78,
    category: 'serums',
    stock: 24,
    image: img('serum.png'),
    images: [img('serum.png')],
    featured: false,
    rating: 4.7,
    numReviews: 109,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Rosehip Face Oil',
    slug: toSlug('Rosehip Face Oil'),
    subtitle: 'Cold-Pressed & Regenerating',
    description: 'Pure cold-pressed rosehip oil rich in essential fatty acids for skin regeneration',
    price: 55,
    category: 'serums',
    stock: 27,
    image: img('oil1.jpeg'),
    images: [img('oil1.jpeg')],
    featured: false,
    rating: 4.6,
    numReviews: 88,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Triple Serum Complex',
    slug: toSlug('Triple Serum Complex'),
    subtitle: 'Anti-Ageing & Firming',
    description: 'Three-phase anti-ageing serum complex with peptides, retinol and hyaluronic acid',
    price: 105,
    category: 'serums',
    stock: 16,
    image: img('serum222.png'),
    images: [img('serum222.png')],
    featured: true,
    tag: 'Best Seller',
    tagType: 'best',
    rating: 4.8,
    numReviews: 167,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Botanical Glow Drops',
    slug: toSlug('Botanical Glow Drops'),
    subtitle: 'Firefly Botanical Blend',
    description: 'Illuminating glow drops with a botanical blend to add radiance to any moisturiser or wear alone',
    price: 74,
    category: 'serums',
    stock: 30,
    image: img('firefly.png'),
    images: [img('firefly.png')],
    featured: true,
    rating: 4.7,
    numReviews: 93,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Brightening Serum',
    slug: toSlug('Brightening Serum'),
    subtitle: 'Vitamin C & Ferulic Acid',
    description: 'Potent vitamin C serum with ferulic acid for maximum antioxidant protection and brightening',
    price: 88,
    category: 'serums',
    stock: 19,
    image: img('banner serum.png'),
    images: [img('banner serum.png')],
    featured: true,
    rating: 4.8,
    numReviews: 144,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Vitamin C Citrus Serum',
    slug: toSlug('Vitamin C Citrus Serum'),
    subtitle: 'Orange & Citrus Bright',
    description: 'Fresh citrus-infused vitamin C serum that brightens, firms and evens skin tone',
    price: 79,
    category: 'serums',
    stock: 23,
    image: img('Firefly_Gemini Flash_Vitamin C serum bottle with orange slices and citrus leaves, _bright fresh aesthetic, 779867.png'),
    images: [img('Firefly_Gemini Flash_Vitamin C serum bottle with orange slices and citrus leaves, _bright fresh aesthetic, 779867.png')],
    featured: false,
    rating: 4.6,
    numReviews: 81,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Luminous Skin Serum',
    slug: toSlug('Luminous Skin Serum'),
    subtitle: 'Botanical Brightening Formula',
    description: 'Botanical brightening serum that visibly evens skin tone and boosts natural luminosity',
    price: 82,
    category: 'serums',
    stock: 21,
    image: img('women22.png'),
    images: [img('women22.png')],
    featured: false,
    rating: 4.5,
    numReviews: 76,
  },

  // ─── MOISTURISERS ─────────────────────────────────────
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Botanical Hydra Cream',
    slug: toSlug('Botanical Hydra Cream'),
    subtitle: 'Rose & Ceramide Complex',
    description: 'Deep hydration cream with rose extract and ceramides to restore the skin barrier',
    price: 72,
    category: 'moisturisers',
    stock: 30,
    image: unsplashImages.moisturizer1,
    images: [unsplashImages.moisturizer1],
    featured: true,
    rating: 4.6,
    numReviews: 89,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Collagen Boost Cream',
    slug: toSlug('Collagen Boost Cream'),
    subtitle: 'Marine Collagen & Peptides',
    description: 'Rich moisturiser packed with marine collagen and peptides to firm and plump skin',
    price: 85,
    category: 'moisturisers',
    stock: 25,
    image: img('collagen-cream.png'),
    images: [img('collagen-cream.png')],
    featured: true,
    rating: 4.7,
    numReviews: 113,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Moisture Surge Cream',
    slug: toSlug('Moisture Surge Cream'),
    subtitle: 'Ceramide & Squalane',
    description: 'Barrier-restoring moisturiser with ceramides and squalane for deep lasting hydration',
    price: 68,
    category: 'moisturisers',
    stock: 30,
    image: img('moisturizer1.png'),
    images: [img('moisturizer1.png')],
    featured: true,
    rating: 4.6,
    numReviews: 74,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Aloe Vera Gel',
    slug: toSlug('Aloe Vera Gel'),
    subtitle: 'Pure & Soothing',
    description: 'Pure aloe vera gel that soothes, hydrates and calms irritated or sun-exposed skin',
    price: 32,
    category: 'moisturisers',
    stock: 50,
    image: img('aloevera.png'),
    images: [img('aloevera.png')],
    featured: true,
    rating: 4.5,
    numReviews: 108,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Soothing Relief Cream',
    slug: toSlug('Soothing Relief Cream'),
    subtitle: 'Oat & Chamomile Calm',
    description: 'Ultra-calming moisturiser with oat extract and chamomile for sensitive and reactive skin',
    price: 50,
    category: 'moisturisers',
    stock: 32,
    image: img('soothingcream.png'),
    images: [img('soothingcream.png')],
    featured: false,
    rating: 4.5,
    numReviews: 57,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Glow Face Cream',
    slug: toSlug('Glow Face Cream'),
    subtitle: 'Brightening & Nourishing',
    description: 'Radiance-boosting day cream with vitamin C and niacinamide for a healthy luminous glow',
    price: 58,
    category: 'moisturisers',
    stock: 36,
    image: img('cream1.png'),
    images: [img('cream1.png')],
    featured: false,
    rating: 4.6,
    numReviews: 81,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Marine Collagen Cream',
    slug: toSlug('Marine Collagen Cream'),
    subtitle: 'Pearl & Marine Collagen',
    description: 'Luxurious cream with pearl extract and marine collagen for visibly firmer, younger-looking skin',
    price: 92,
    category: 'moisturisers',
    stock: 18,
    image: img('Firefly_Collagen face cream with pearl and marine elements, _soft blue and white tones, elega 779867.png'),
    images: [img('Firefly_Collagen face cream with pearl and marine elements, _soft blue and white tones, elega 779867.png')],
    featured: true,
    tag: 'Best Seller',
    tagType: 'best',
    rating: 4.8,
    numReviews: 142,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Women Glow Ritual Set',
    slug: toSlug('Women Glow Ritual Set'),
    subtitle: 'Complete Skincare Routine',
    description: 'Complete glow ritual set with cleanser, serum, moisturiser and SPF for your full routine',
    price: 145,
    comparePrice: 180,
    category: 'moisturisers',
    stock: 12,
    image: img('women banner.png'),
    images: [img('women banner.png')],
    featured: true,
    tag: 'Sale',
    tagType: 'sale',
    rating: 4.9,
    numReviews: 201,
  },

  // ─── MASKS ────────────────────────────────────────────
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Purifying Clay Mask',
    slug: toSlug('Purifying Clay Mask'),
    subtitle: 'Kaolin & Green Tea',
    description: 'Deep-cleansing clay mask with kaolin and green tea to purify pores and balance skin',
    price: 54,
    category: 'masks',
    stock: 40,
    image: unsplashImages.mask1,
    images: [unsplashImages.mask1],
    featured: true,
    rating: 4.5,
    numReviews: 67,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Black Purifying Mask',
    slug: toSlug('Black Purifying Mask'),
    subtitle: 'Activated Charcoal & Clay',
    description: 'Deep-pore purifying mask with activated charcoal and kaolin clay to draw out impurities',
    price: 48,
    category: 'masks',
    stock: 40,
    image: img('blackmask.png'),
    images: [img('blackmask.png')],
    featured: true,
    tag: 'Best Seller',
    tagType: 'best',
    rating: 4.7,
    numReviews: 145,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Brightening Face Mask',
    slug: toSlug('Brightening Face Mask'),
    subtitle: 'Vitamin C & Turmeric',
    description: 'Illuminating mask with vitamin C and turmeric to even skin tone and boost radiance',
    price: 44,
    category: 'masks',
    stock: 35,
    image: img('mask1.jpeg'),
    images: [img('mask1.jpeg')],
    featured: false,
    rating: 4.5,
    numReviews: 62,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Pink Clay Rose Mask',
    slug: toSlug('Pink Clay Rose Mask'),
    subtitle: 'Rose Petal & Pink Clay',
    description: 'Softening pink clay mask with dried rose petals for a radiant porcelain complexion',
    price: 49,
    category: 'masks',
    stock: 38,
    image: img('Firefly_Gemini Flash_Pink clay face mask in open jar, dried rose petals and pink clay powder, _soft pink m 779867.png'),
    images: [img('Firefly_Gemini Flash_Pink clay face mask in open jar, dried rose petals and pink clay powder, _soft pink m 779867.png')],
    featured: true,
    tag: 'New',
    tagType: 'new',
    rating: 4.6,
    numReviews: 69,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Matcha Detox Mask',
    slug: toSlug('Matcha Detox Mask'),
    subtitle: 'Green Tea & Antioxidants',
    description: 'Antioxidant-rich matcha mask that detoxifies, brightens and refines skin texture',
    price: 46,
    category: 'masks',
    stock: 35,
    image: img('Firefly_Green matcha face mask jar with green tea leaves and powder, _white minimal backgroun 779867.png'),
    images: [img('Firefly_Green matcha face mask jar with green tea leaves and powder, _white minimal backgroun 779867.png')],
    featured: false,
    rating: 4.6,
    numReviews: 74,
  },

  // ─── CLEANSERS ────────────────────────────────────────
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Daily Foam Cleanser',
    slug: toSlug('Daily Foam Cleanser'),
    subtitle: 'Gentle & Balancing',
    description: 'Gentle foaming cleanser that removes impurities without stripping the skin',
    price: 34,
    category: 'cleansers',
    stock: 50,
    image: img('cleanser1.png'),
    images: [img('cleanser1.png')],
    featured: false,
    rating: 4.5,
    numReviews: 83,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Gentle Cleansing Balm',
    slug: toSlug('Gentle Cleansing Balm'),
    subtitle: 'Chamomile & Jojoba',
    description: 'Melt-away cleansing balm with chamomile and jojoba to dissolve makeup and impurities',
    price: 38,
    category: 'cleansers',
    stock: 45,
    image: unsplashImages.cleanser1,
    images: [unsplashImages.cleanser1],
    featured: false,
    rating: 4.7,
    numReviews: 92,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Micellar Cleansing Water',
    slug: toSlug('Micellar Cleansing Water'),
    subtitle: 'No-Rinse Makeup Remover',
    description: 'Gentle micellar water that effortlessly lifts makeup and impurities without rubbing or rinsing',
    price: 26,
    category: 'cleansers',
    stock: 60,
    image: unsplashImages.cleanser2,
    images: [unsplashImages.cleanser2],
    featured: false,
    rating: 4.5,
    numReviews: 96,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'AHA Exfoliating Cleanser',
    slug: toSlug('AHA Exfoliating Cleanser'),
    subtitle: 'Glycolic & Lactic Acid',
    description: 'Resurfacing gel cleanser with glycolic and lactic acid to smooth texture and brighten dull skin',
    price: 40,
    category: 'cleansers',
    stock: 40,
    image: unsplashImages.serum3,
    images: [unsplashImages.serum3],
    featured: true,
    tag: 'New',
    tagType: 'new',
    rating: 4.6,
    numReviews: 77,
  },

  // ─── SUNCARE ──────────────────────────────────────────
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'SPF 50 Daytime Shield',
    slug: toSlug('SPF 50 Daytime Shield'),
    subtitle: 'Invisible Mineral Sunscreen',
    description: 'Featherlight mineral sunscreen with SPF 50 protection and invisible finish',
    price: 46,
    category: 'suncare',
    stock: 50,
    image: unsplashImages.suncare1,
    images: [unsplashImages.suncare1],
    featured: false,
    rating: 4.4,
    numReviews: 55,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'SPF 50 Sunscreen Mist',
    slug: toSlug('SPF 50 Sunscreen Mist'),
    subtitle: 'Mineral Sun Protection',
    description: 'Ultra-light mineral sunscreen mist with SPF 50 for effortless on-the-go reapplication',
    price: 52,
    category: 'suncare',
    stock: 42,
    image: img('openart-image_1779246961186_5c90a2cd_1779246961341_be072d89.png'),
    images: [img('openart-image_1779246961186_5c90a2cd_1779246961341_be072d89.png')],
    featured: false,
    rating: 4.5,
    numReviews: 63,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Hydra-Shield SPF 50+',
    slug: toSlug('Hydra-Shield SPF 50+'),
    subtitle: 'Moisturising Sun Protection',
    description: 'Deeply hydrating SPF 50+ sunscreen with hyaluronic acid for plump protected skin all day',
    price: 54,
    category: 'suncare',
    stock: 38,
    image: unsplashImages.serum4,
    images: [unsplashImages.serum4],
    featured: true,
    tag: 'Best Seller',
    tagType: 'best',
    rating: 4.8,
    numReviews: 119,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Mineral Glow SPF 30',
    slug: toSlug('Mineral Glow SPF 30'),
    subtitle: 'Tinted Mineral Sunscreen',
    description: 'Lightweight tinted mineral SPF 30 that blurs imperfections and protects against UVA and UVB',
    price: 42,
    category: 'suncare',
    stock: 45,
    image: unsplashImages.serum5,
    images: [unsplashImages.serum5],
    featured: false,
    tag: 'New',
    tagType: 'new',
    rating: 4.5,
    numReviews: 73,
  },

  // ─── TONERS ───────────────────────────────────────────
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Balancing Toner',
    slug: toSlug('Balancing Toner'),
    subtitle: 'AHA & Witch Hazel',
    description: 'Exfoliating toner with AHA and witch hazel to refine pores and even skin texture',
    price: 36,
    category: 'toners',
    stock: 55,
    image: img('tone1.png'),
    images: [img('tone1.png')],
    featured: false,
    tag: 'Sale',
    tagType: 'sale',
    rating: 4.4,
    numReviews: 60,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Hyaluronic Mist',
    slug: toSlug('Hyaluronic Mist'),
    subtitle: '3-Weight HA Complex',
    description: 'Refreshing facial mist with three molecular weights of hyaluronic acid for all-day hydration',
    price: 29,
    category: 'toners',
    stock: 60,
    image: unsplashImages.moisturizer2,
    images: [unsplashImages.moisturizer2],
    featured: false,
    rating: 4.3,
    numReviews: 41,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Rose Water Toner',
    slug: toSlug('Rose Water Toner'),
    subtitle: 'Hydrating & Soothing',
    description: 'Pure rose water toner that hydrates, soothes and preps skin to absorb serums better',
    price: 32,
    category: 'toners',
    stock: 50,
    image: unsplashImages.mask2,
    images: [unsplashImages.mask2],
    featured: false,
    rating: 4.5,
    numReviews: 84,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Niacinamide Essence',
    slug: toSlug('Niacinamide Essence'),
    subtitle: '10% Niacinamide & Zinc',
    description: 'Pore-minimising essence with 10% niacinamide and zinc to control oil and even skin tone',
    price: 38,
    category: 'toners',
    stock: 45,
    image: unsplashImages.toner1,
    images: [unsplashImages.toner1],
    featured: true,
    tag: 'Best Seller',
    tagType: 'best',
    rating: 4.7,
    numReviews: 116,
  },

  // ─── EYES ─────────────────────────────────────────────
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Eye Contour Cream',
    slug: toSlug('Eye Contour Cream'),
    subtitle: 'Caffeine & Peptide Lift',
    description: 'Targeted eye cream with caffeine and peptides to reduce puffiness and dark circles',
    price: 62,
    category: 'eyes',
    stock: 35,
    image: unsplashImages.eye1,
    images: [unsplashImages.eye1],
    featured: false,
    rating: 4.6,
    numReviews: 78,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Advanced Eye Cream',
    slug: toSlug('Advanced Eye Cream'),
    subtitle: 'Retinol & Vitamin K',
    description: 'Intensive eye treatment with retinol and vitamin K to visibly reduce fine lines',
    price: 65,
    category: 'eyes',
    stock: 28,
    image: img('eye-cream.png'),
    images: [img('eye-cream.png')],
    featured: false,
    rating: 4.7,
    numReviews: 101,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Brightening Eye Serum',
    slug: toSlug('Brightening Eye Serum'),
    subtitle: 'Vitamin C & Kojic Acid',
    description: 'Targeted brightening serum with vitamin C and kojic acid to visibly lighten dark circles',
    price: 58,
    category: 'eyes',
    stock: 30,
    image: unsplashImages.eye2,
    images: [unsplashImages.eye2],
    featured: true,
    tag: 'New',
    tagType: 'new',
    rating: 4.6,
    numReviews: 93,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Firming Eye Gel',
    slug: toSlug('Firming Eye Gel'),
    subtitle: 'Collagen & Hyaluronic Acid',
    description: 'Cooling gel with collagen and hyaluronic acid to firm, smooth and de-puff the eye area',
    price: 55,
    category: 'eyes',
    stock: 33,
    image: unsplashImages.moisturizer3,
    images: [unsplashImages.moisturizer3],
    featured: false,
    tag: 'Best Seller',
    tagType: 'best',
    rating: 4.8,
    numReviews: 107,
  },
];

const seedProducts = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ MongoDB Connected');

    await Product.deleteMany();
    console.log('🗑️  Products cleared');

    const insertedProducts = await Product.insertMany(products);
    console.log(`✅ ${insertedProducts.length} products seeded successfully`);
    
    // Display first few product IDs for reference
    console.log('\n📋 Sample Product IDs:');
    insertedProducts.slice(0, 5).forEach(p => {
      console.log(`  ${p.name}: ${p._id}`);
    });

    process.exit(0);
  } catch (error) {
    console.error('❌ Seeder error:', error);
    process.exit(1);
  }
};

seedProducts();